# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# $ rm db_ip.txt | vagrant up | python store_ip.py

Vagrant.configure("2") do |config|
    config.vm.box = 'digital_ocean'
    config.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    config.ssh.private_key_path = '~/.ssh/do_ssh_key'

    config.vm.define "webserver", primary: false do |server|
  
      server.vm.provider :digital_ocean do |provider|
        provider.ssh_key_name = "do_ssh_key"
        provider.token = ENV["DIGITAL_OCEAN_TOKEN"]
        provider.image = 'ubuntu-22-04-x64'
        provider.region = 'fra1'
        provider.size = 's-1vcpu-1gb'
        provider.privatenetworking = true
      end

      server.vm.hostname = "webserver"

      server.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        echo "Installing nodejs and npm"
        sudo apt-get install -y nodejs npm
        echo "Cloning repository"
        git clone https://github.com/nikogio/DevOps-group_s.git
        cd DevOps-group_s/itu-minitwit-node
        echo "Installing dependencies"
        npm install
      SHELL
    end
    config.vm.provision "shell", privileged: false, inline: <<-SHELL
      sudo apt-get update
    SHELL
end